USE ROLE ACCOUNTADMIN;
USE DATABASE NORTHERN_RIDGE_DB;
USE SCHEMA PUBLIC;

-- 1. Create a secret containing your GitHub Personal Access Token
CREATE OR REPLACE SECRET GITHUB_DBT_PAT
  TYPE = PASSWORD
  USERNAME = 'fabmel1'
  PASSWORD = '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';

-- 2. Create an API Integration pointing to GitHub
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/fabmel1/')
  ALLOWED_AUTHENTICATION_SECRETS = (NORTHERN_RIDGE_DB.PUBLIC.GITHUB_DBT_PAT)
  ENABLED = TRUE;

USE ROLE NR_DATA_ENGINEER;
USE DATABASE NORTHERN_RIDGE_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE GIT REPOSITORY NORTHERN_RIDGE_DB.BRONZE.GIT_DBT_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = NORTHERN_RIDGE_DB.PUBLIC.GITHUB_DBT_PAT
  ORIGIN = 'https://github.com/fabmel1/northern-ridge-data-platform.git';  

  -- Fetch latest code from GitHub
ALTER GIT REPOSITORY NORTHERN_RIDGE_DB.BRONZE.GIT_DBT_REPO FETCH;

-- List files inside your repo directly within Snowflake
LS @NORTHERN_RIDGE_DB.BRONZE.GIT_DBT_REPO/branches/main/;