-- Run models in Snowflake

--Sync with GitHub
ALTER GIT REPOSITORY NORTHERN_RIDGE_DB.BRONZE.GIT_DBT_REPO FETCH;

--Re-create the DBT project
CREATE OR REPLACE DBT PROJECT NORTHERN_RIDGE_DB.SILVER.NR_DBT_PROJECT
  FROM @NORTHERN_RIDGE_DB.BRONZE.GIT_DBT_REPO/branches/main/;

  -- Run DBT models
EXECUTE DBT PROJECT NORTHERN_RIDGE_DB.SILVER.NR_DBT_PROJECT 
  ARGS = 'run';